# This is a basic workflow that is manually triggered

name: Manual workflow for branch builds

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and deploy with Maven
      run: |
        version_prefix=`mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout --file warehouse/pom.xml | awk -F. '{print $1"."$2}'`
        version="$version_prefix.${{github.run_number}}-b$GITHUB_SHA"
        echo "Setting artifact version to $version..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
